Update JenkinsfileProvision

diff --git a/JenkinsfileProvision b/JenkinsfileProvision
--- a/JenkinsfileProvision
+++ b/JenkinsfileProvision
@@ -29,15 +29,15 @@ pipeline {
         choice(name: 'atlas_project', choices: ['wo-sre-dev-cluster(625e8f54c6f9c330400eb8c9)', 'wo-sre-pre-prod(6294afcd616aad482736ec3d)', 'wo-sre-prod(6294ae49a574e03a2abfb428)', 'wo-sre-stg-cluster(6273639f0dbf34569a3c0b2a)'], description: 'Select Project from the list.Respective Project ID mentioned in parenthesis for reference')
         // string(name: 'atlas_cluster_name', defaultValue: '', description: 'Atlas cluster name in format: wo-<env>-<instance>-mongodb Ex. wo-dev-lcap-mongodb')
         // validatingString(name: 'atlas_cluster_name', defaultValue: '', regex: '^wo?-.+?-.+?-mongodb', failedValidationMessage: 'Validation failed! : Enter cluster name in format: wo-<env>-<instance>-mongodb', description: 'Atlas cluster name in format: wo-<env>-<instance>-mongodb Ex. wo-dev-lcap-mongodb')
-        validatingString(name: 'atlas_instance_name', defaultValue: '', regex: '^.+?-.+?-.+', failedValidationMessage: 'Validation failed! : Enter instance name in format: wo-<env>-<instance>', description: 'Atlas instance name in format: wo-<env>-<instance> Ex. wo-dev-lcap')
-        separator(name: 'VPC Peering Related Parameters', sectionHeader: 'VPC Peering Related Parameters')
+        validatingString(name: 'atlas_instance_name', defaultValue: '', regex: '^.+?-.+?-.+', failedValidationMessage: 'Validation failed! : Enter instance name in format: wo-<env>-<instance>', description: 'Atlas instance name in format: wo-<env>-<instance> Ex. wo-dev-lcap. This will create mongo cluster with name wo-<env>-<instance>-mongodb in approx. 10 minutes. A database user will be created with name <instance>-mongodb.')
+        separator(name: 'VPC Peering Related Parameters', sectionHeader: 'VPC Peering Related Parameters (not needed for dev environmet)')
         // string(name: 'aws_region', defaultValue: 'ap-south-1', description: 'AWS Region in which cluster needs to be deployed.')
         // string(name: 'atlas_vpc_cidr', defaultValue: '', description: 'Atlas VPC CIDR block')
         string(name: 'aws_act_id', defaultValue: '', description: 'AWS account in which service needs to be deployed.')
-        string(name: 'aws_vpc_id', defaultValue: '', description: 'AWS VPC ID for peering')
-        string(name: 'aws_vpc_cidr', defaultValue: '', description: 'AWS VPC CIDR block')
-        //string(name: 'subnet_a_cidr', defaultValue: '', description: 'AWS VPC subnet a CIDR block')
-        //string(name: 'subnet_b_cidr', defaultValue: '', description: 'AWS VPC subnet b CIDR block')
+        string(name: 'aws_vpc_id', defaultValue: '', description: 'AWS VPC ID for peering Ex. vpc-xxxxxxxxxxx')
+        string(name: 'aws_vpc_cidr', defaultValue: '', description: 'AWS VPC IPv4 CIDR block in format: x.x.x.x/x Ex. 10.0.0.0/16. IPv4 CIDR block of VPC must not overlap')
+    //string(name: 'subnet_a_cidr', defaultValue: '', description: 'AWS VPC subnet a CIDR block')
+    //string(name: 'subnet_b_cidr', defaultValue: '', description: 'AWS VPC subnet b CIDR block')
     }
     environment {
         BRANCH_NAME_ENV = 'mongo-atlas-provisioning'
@@ -55,16 +55,16 @@ pipeline {
     // TF_LOG="TRACE"
     }
     stages {
-       stage('checkout') {
-            steps {
-                git branch: "${BRANCH_NAME_ENV}", credentialsId: 'git-cred-for-MongoDB', url: 'https://github.ibm.com/WatsonOrchestrate/wo-mongodb-atlas-automation.git'
-            }
-        }
+        // stage('checkout') {
+            // steps {
+                // git branch: "${BRANCH_NAME_ENV}", credentialsId: 'git-cred-for-MongoDB', url: 'https://github.ibm.com/WatsonOrchestrate/wo-mongodb-atlas-automation.git'
+            // }
+        // }
         stage('Variable Processing') {
             steps {
                 script {
                     def res = 0
-                    res = sh(script: '''
+                    res = sh(script: '''#!/bin/bash
                     # Convert Selected Atlas region to lowercase to set aws region & export
                     # export AWS_DEFAULT_REGION="$(echo "$atlas_region" | tr '[:upper:]' '[:lower:]' | sed "s/_/-/g")"
                     # Split atlas_project into ATLAS_PROJECT_NAME and ATLAS_PROJECT_ID
@@ -85,6 +85,13 @@ pipeline {
                         exit 1
                     fi
                     if [ ! -z "$aws_vpc_id" ]; then
+                        if [ -z "$(echo "$aws_act_id" | grep -E '^[[:digit:]]{1,}$')" ]; then
+                             echo "Invalid id"
+                             exit 1
+                        elif [ $(echo "$aws_act_id" | awk '{print length}') != 12 ]; then
+                               echo "Invalid id"
+                               exit 1
+                        fi
                         if [ -z $(echo "$aws_vpc_id" | grep -E '^vpc.?-.+') ]; then
                             echo "Invalid VPC Id"
                             exit 1
@@ -121,9 +128,9 @@ pipeline {
             steps {
                 script {
                     def res = 0
-                    res = sh(script: '''
+                    res = sh(script: '''#!/bin/bash
                         # export ATLAS_PROJECT_ID="$(echo "$atlas_project"|cut -f 2 -d "("|cut -f 1 -d ")")"
-                        clusters_json="$(curl --user "${atlas_public_key}:${atlas_private_key}" --digest -X GET "https://cloud.mongodb.com/api/atlas/v1.0/groups/${ATLAS_PROJECT_ID}/clusters" | jq ".results[].name")"
+                        clusters_json="$(curl --silent --user "${atlas_public_key}:${atlas_private_key}" --digest -X GET "https://cloud.mongodb.com/api/atlas/v1.0/groups/${ATLAS_PROJECT_ID}/clusters" | jq ".results[].name")"
                         echo "clusters_json=$clusters_json"
                         if [ ! -z "$clusters_json" ]; then
                             if echo "$clusters_json" | grep -E "${atlas_cluster_name}" 1>/dev/null 2>&1; then
@@ -149,7 +156,7 @@ pipeline {
         stage('Terraform init') {
             steps {
                 catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
-                    sh '''
+                    sh '''#!/bin/bash
                     rm -rf .terraform .terraform.lock.hcl terraform.tfstate.d
                     # Split atlas_project into ATLAS_PROJECT_NAME and ATLAS_PROJECT_ID
                     # export ATLAS_PROJECT_NAME="$(echo "$atlas_project"|cut -f 1 -d "(")"
@@ -162,8 +169,8 @@ pipeline {
         stage('Terraform Plan') {
             steps {
                 catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
-                  wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[password: atlas_dbpassword]]]) {
-                    sh '''
+                    wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[password: atlas_dbpassword]]]) {
+                        sh '''#!/bin/bash
                     echo "State File Location: mongo-atlas-provisioning-automation-state-bucket > ${ATLAS_PROJECT_NAME}/${atlas_cluster_name}/terraform.tfstate"
                     # Split atlas_project into ATLAS_PROJECT_NAME and ATLAS_PROJECT_ID
                     # export ATLAS_PROJECT_NAME="$(echo "$atlas_project"|cut -f 1 -d "(")"
@@ -190,14 +197,14 @@ pipeline {
                       -var atlas_dbuser=${atlas_dbuser} \
                       -out my.plan
                    '''
-                  }
+                    }
                 }
             }
         }
         stage('Terraform Apply') {
             steps {
                 catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
-                    sh '''
+                    sh '''#!/bin/bash
                      # export ATLAS_PROJECT_ID="$(echo "$atlas_project"|cut -f 2 -d "("|cut -f 1 -d ")")"
                      # export atlas_dbuser="$(echo "$instance_name-mongodb")"
                      echo "terraform Apply"
